version: '3.6'

services:
  caddy:
    image: caddy:2
    container_name: shadow-caddy2
    restart: always
    networks:
      - reverse-public
    dns:
      # google
      - 8.8.8.8
      # opendsn
      - 208.67.222.222
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./caddy/caddy_cert:/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory
      - ./caddy/caddy_config:/config
      - ./caddy/www:/usr/share/caddy/
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.vless-vision-caddy.entrypoints=web"
      - "traefik.http.routers.vless-vision-caddy.rule=Host(`${SS_DOMAIN}`)"
      - "traefik.http.routers.vless-vision-caddy.service=vless-vision-caddy"
      - "traefik.http.services.vless-vision-caddy.loadbalancer.server.port=80"

      - "traefik.http.routers.vless-vision-caddy-acme.entrypoints=web"
      - "traefik.http.routers.vless-vision-caddy-acme.rule=Host(`${SS_DOMAIN}`) && Path(`/.well-known/acme-challenge/`) && Method(`GET`) "
      - "traefik.http.routers.vless-vision-caddy-acme.service=vless-vision-caddy-acme"
      - "traefik.http.services.vless-vision-caddy-acme.loadbalancer.server.port=80"

  xray:
    image: teddysun/xray:latest
    container_name: shadow-xray
    restart: always
    volumes:
      - ./xray/config.json:/etc/xray/config.json
      - ./caddy/caddy_cert:/cert
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    depends_on:
      - caddy
    networks:
      - reverse-public
    labels:
      - "traefik.enable=true"
      - "traefik.tcp.routers.vless-vision-xray.rule=HostSNI(`${SS_DOMAIN}`)"
      - "traefik.tcp.routers.vless-vision-xray.tls.passthrough=true"
      - "traefik.tcp.routers.vless-vision-xray.service=vless-vision-xray"
      - "traefik.tcp.services.vless-vision-xray.loadbalancer.server.port=443"

networks:
  reverse-public:
    external: true
